### PR TITLE
Fix parallel data providers

### LINKED ISSUE #4: `@DataProvider(parallel = true)` should be supported
Currently, this throws an exception.

Reproducer: https://github.com/nebula-plugins/gradle-nebula-integration/tree/a2950c001af725a4ea185b86dbbaf34795ee5407/testng-junit-platform

### PR DESCRIPTION
**Pull request by marcphilipp**
Since `org.testng.ITestNGMethod#getId` is not reliable, the execution
listener now uses the ITestResult as a key to find the correct
invocation and does not eagerly report the method container as finished
but relies on onAfterClass to do so. This approach is also used by
Gradle's listener implementation so it should be robust.

Fixes #4.

### CODE REVIEW

File: src/main/java/org/junit/support/testng/engine/ExecutionListener.java [hunk 1]
```diff
@@ -229,7 +220,7 @@ private Throwable chain(Set<Throwable> failures) {
 	static class MethodProgress {
 		final ITestNGMethod method;
 		final MethodDescriptor descriptor;
-		final ConcurrentMap<String, InvocationDescriptor> invocations = new ConcurrentHashMap<>();
+		final ConcurrentMap<ITestResult, InvocationDescriptor> invocations = new ConcurrentHashMap<>();
```
Comment (leonard84) [inline src/main/java/org/junit/support/testng/engine/ExecutionListener.java:223]: Are we sure that `ITestResult` is always well behaved to be used as a key?

Comment (marcphilipp) [reply src/main/java/org/junit/support/testng/engine/ExecutionListener.java:223]: Gradle uses it as a key as well so I'm fairly sure.

**Review by leonard84 — APPROVED** [review]
